framework:
    asset_mapper:
        paths:
            - assets/
            - assets/landing/
            - assets/landing/vendors/
        missing_import_mode: strict
        extensions:
            - .js
            - .css
            - .png
            - .jpg
            - .jpeg
            - .svg
            - .gif
            - .woff
            - .woff2
            - .ttf
            - .eot

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
