framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys
        prefix_seed: abeille_solidaire

        # System cache
        system: cache.adapter.system
        
        # Default cache pool
        app: cache.adapter.filesystem
        
        # Configure cache pools
        pools:
            cache.landing:
                adapter: cache.adapter.filesystem
                tags: true
                default_lifetime: 3600
