framework:
    cache:
        # Unique name of your landing: used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # System settings
        system: cache.adapter.system
        # Default cache pool
        app: cache.adapter.filesystem
        # Landing page cache pool
        landing:
            adapter: cache.adapter.filesystem
            default_lifetime: 3600
        # Other pools if needed
        pools:
            cache.landing:
                adapter: cache.adapter.filesystem
                tags: true
