framework:
    rate_limiter:
        limiters:
            registration_limiter:
                policy: 'sliding_window'
                limit: 5  # Already set to 5 attempts
                interval: '1 hour'
