twig:
    file_name_pattern: "*.twig"
    globals:
        site_name: "%env(SITE_NAME)%"
        recaptcha_site_key: "%app.recaptcha.site_key%"
        stripe_public_key: "%stripe.public_key%"
        stripe_client_secret: "%stripe.secret_key%"
        site_config:
            description: "Notre vision est de créer un modèle d'entreprise radicalement différent, axé sur l'économie solidaire. Nous croyons en un modèle où la réussite de l'entreprise est mesurée non seulement par ses profits, mais aussi par son impact positif sur la société. Nous invitons ceux qui partagent notre vision à se joindre à nous dans cette aventure."
            contact:
                address: "71-75 SHELTON STREET COVENT GARDEN LONDON ROYAUME-UNI WC2H 9JQ"
                email: "support@abeilleolidaire.club"
                phone: "757840955"
                secondary_address: "71-75 SHELTON STREET COVENT GARDEN LONDON ROYAUME-UNI WC2H 9JQ"
            social:
                twitter: "#"
                facebook: "#"
                pinterest: "#"
                instagram: "#"
            footer_sections:
                about:
                    - { title: "Qui sommes-nous ?", url: "/about" }
                    - { title: "Faire un don", url: "/register" }
                for_you:
                    - { title: "FAQ", url: "/faq" }
                    - { title: "Contact", url: "/contact" }

when@test:
    twig:
        strict_variables: true
