vich_uploader:
    db_driver: orm
    
    mappings:
        uploads:
            uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/public/uploads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            
        slides:
            uri_prefix: /uploads/slides
            upload_destination: '%kernel.project_dir%/public/uploads/slides'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true

        events:
            uri_prefix: /uploads/events
            upload_destination: '%kernel.project_dir%/public/uploads/events'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        news:
            uri_prefix: /uploads/news
            upload_destination: '%kernel.project_dir%/public/uploads/news'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
