name: abeille-solidaire
recipe: symfony
config:
  webroot: public
  php: '8.4'
  via: nginx
  database: postgres

services:
  appserver:
    build_as_root:
      - curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh' | bash
      - apt update && apt install -y symfony-cli
    build:
      - |
        if [ ! -f composer.json ]; then
          mkdir tmp && cd tmp
          symfony new --version=7.2 --webapp --no-git .
          # Move all hidden files except . and ..
          for file in .[!.]*; do
            if [ -e "$file" ]; then
              mv "$file" ../
            fi
          done
          # Move all regular files and directories
          for file in *; do
            mv "$file" ../
          done
          cd ..
          rm -rf tmp
          composer install
        fi

  pgadmin:
    type: compose
    app_mount: false
    ssl: false
    services:
      image: dpage/pgadmin4
      command: /entrypoint.sh
      restart: always
      ports:
        - :80
    overrides:
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@example.com
        PGADMIN_DEFAULT_PASSWORD: password

  mailhog:
    type: mailhog
    hogfrom:
      - appserver

proxy:
  pgadmin:
    - pgadmin.abeille-solidaire.lndo.site
  mailhog:
    - mail.abeille-solidaire.lndo.site

environment:
  APP_ENV: dev
  APP_DEBUG: 1
