services:
  php:
    image: ${IMAGES_PREFIX:-}app-php
    restart: unless-stopped
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
      DATABASE_URL: ${DATABASE_URL}
      # The two next lines can be removed after initial installation
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
      STABILITY: ${STABILITY:-stable}
      STRIPE_PUBLIC_KEY: ${STRIPE_PUBLIC_KEY:-}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY:-}
      COINPAYMENTS_PUBLIC_KEY: ${COINPAYMENTS_PUBLIC_KEY:-}
      COINPAYMENTS_PRIVATE_KEY: ${COINPAYMENTS_PRIVATE_KEY:-}
      COINPAYMENTS_IPN_SECRET: ${COINPAYMENTS_IPN_SECRET:-}
    volumes:
      - .:/app # Add this line to mount your project files
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config:
    external: true
