# Development environment override
services:
  php:
    build:
      context: .
      target: frankenphp_dev
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./:/app:cached
      - ./vendor:/app/vendor:delegated
      # Exclude vendor from source mount to preserve container's vendor
      - /app/vendor
    environment:
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true
