services:
  php:
    image: ${IMAGES_PREFIX:-}app-php
    restart: unless-stopped
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
      DATABASE_URL: ${DATABASE_URL:-}
      APP_SECRET: ${APP_SECRET}
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
      STABILITY: ${STABILITY:-stable}
      SYMFONY_PROCESS_TIMEOUT: 900
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./public/uploads:/app/public/uploads

volumes:
  caddy_data:
  caddy_config:
