services:
  php:
    build:
      context: .
      target: frankenphp_dev
    volumes:
      - ./:/app
      - /app/vendor
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      - host.docker.internal:host-gateway
    tty: true
