services:
  php:
    build:
      context: .
      target: frankenphp_dev
    volumes:
      - ./:/app
      - type: bind
        source: ${PWD}/frankenphp/Caddyfile
        target: /etc/caddy/Caddyfile
        read_only: true
      - type: bind
        source: ${PWD}/frankenphp/conf.d/20-app.dev.ini
        target: /usr/local/etc/php/app.conf.d/20-app.dev.ini
        read_only: true
      - /app/vendor
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      - host.docker.internal:host-gateway
    tty: true
